var ctx;
var intervalId, currentObjectId;
var WIDTH, HEIGHT;
var NROWS, NCOLS;
var TETRIS_BEGIN, TETRIS_END;
var cells;
var BLOCK_WIDTH;
var current_obj;
var X_START;
var Y_START;
var rightDown, leftDown, downDown, upDown, spaceDown;
var DROP_INTERVAL;
var REFRESH_RATE;
var SCORE;
var LEVEL;
